
import streamlit as st
import pandas as pd
import os
from src.fetch_onrrp import ONRRPFetcher
from src.fetch_reserves import ReservesFetcher
from src.fetch_sofr import SOFRFetcher
from src.fetch_srf import SRFFetcher
from src.fetch_treasury import TreasuryFetcher
from src.config import THRESHOLDS

# Load visualization field descriptions
fields_csv = os.path.join(os.path.dirname(__file__), "data", "visualization_fields.csv")
fields_df = pd.read_csv(fields_csv)
def get_field_description(viz, field):
	match = fields_df[(fields_df["visualization"] == viz) & (fields_df["field"] == field)]
	if not match.empty:
		return match.iloc[0]["description"]
	return "No description available for this field."


st.set_page_config(page_title="Liquidity Stress Dashboard", layout="wide")
st.title("Federal Liquidity Stress Dashboard")



# --- ALERT LOGIC & SUMMARY PANEL ---
def get_alert_level(indicator, value):
    if indicator == "ON RRP":
        if value is None:
            return "🔴", "No data"
        if value > THRESHOLDS['onrrp_stress'] * 1e9:
            return "⚠️", f"Stress: {value/1e9:.1f}B > {THRESHOLDS['onrrp_stress']}B"
        return "🟢", f"Normal: {value/1e9:.1f}B"
    if indicator == "Bank Reserves":
        if value is None:
            return "🔴", "No data"
        if value < THRESHOLDS['reserves_low'] * 1e9:
            return "⚠️", f"Stress: {value/1e9:.1f}B < {THRESHOLDS['reserves_low']}B"
        return "🟢", f"Normal: {value/1e9:.1f}B"
    if indicator == "SOFR":
        if value is None:
            return "🔴", "No data"
        if value > THRESHOLDS['sofr_spike']:
            return "⚠️", f"Stress: {value:.3f} > {THRESHOLDS['sofr_spike']:.3f}"
        return "🟢", f"Normal: {value:.3f}"
    if indicator == "SRF":
        if value is None:
            return "🔴", "No data"
        if value > THRESHOLDS['srf_usage'] * 1e9:
            return "🚨", f"Emergency: {value/1e9:.1f}B > {THRESHOLDS['srf_usage']}B"
        return "🟢", f"Normal: {value/1e9:.1f}B"
    if indicator == "Treasury":
        if value is None:
            return "🔴", "No data"
        if value > THRESHOLDS['treasury_issuance_high'] * 1e9:
            return "⚠️", f"Stress: {value/1e9:.1f}B > {THRESHOLDS['treasury_issuance_high']}B"
        return "🟢", f"Normal: {value/1e9:.1f}B"
    return "🔴", "No data"

def get_latest_value(df, col):
    if df is None or col not in df.columns:
        return None
    try:
        return float(df[col].dropna().iloc[-1])
    except Exception:
        return None



# ...existing code...

# Data fetchers
onrrp_fetcher = ONRRPFetcher()
reserves_fetcher = ReservesFetcher()
sofr_fetcher = SOFRFetcher()
srf_fetcher = SRFFetcher()
treasury_fetcher = TreasuryFetcher()

# Load data from CSVs (already generated by dashboard.py)
data_dir = os.path.join(os.path.dirname(__file__), "data")
def load_data(path, fetcher=None):
    # Try API fetcher first if provided
    if fetcher is not None:
        try:
            today = pd.Timestamp.today()
            start_date = today - pd.Timedelta(days=30)
            end_date = today
            # Convert to Python datetime for fetchers
            start_dt = start_date.to_pydatetime()
            end_dt = end_date.to_pydatetime()
            df = fetcher.fetch_data(start_dt, end_dt) if hasattr(fetcher, 'fetch_data') else fetcher()
            if df is not None and not df.empty:
                return df, "API"
        except Exception:
            pass
    # Fallback to file
    try:
        df = pd.read_csv(path)
        if df is not None and not df.empty:
            return df, "File"
    except Exception:
        pass
    return None, None

onrrp_df, onrrp_source = load_data(os.path.join(data_dir, "onrrp_data.csv"), onrrp_fetcher)
reserves_df, reserves_source = load_data(os.path.join(data_dir, "reserves_data.csv"), reserves_fetcher)
sofr_df, sofr_source = load_data(os.path.join(data_dir, "sofr_data.csv"), sofr_fetcher)
srf_df, srf_source = load_data(os.path.join(data_dir, "srf_data.csv"), srf_fetcher)
treasury_df, treasury_source = load_data(os.path.join(data_dir, "treasury_data.csv"), treasury_fetcher)

with st.container():
    st.subheader("System Stress Summary")
    summary_cols = st.columns(5)
    # ON RRP
    onrrp_val = get_latest_value(onrrp_df, onrrp_df.columns[0]) if onrrp_df is not None else None
    icon, msg = get_alert_level("ON RRP", onrrp_val)
    summary_cols[0].markdown(f"**ON RRP** {icon}<br>{msg}", unsafe_allow_html=True)
    # Bank Reserves
    reserves_val = get_latest_value(reserves_df, reserves_df.columns[0]) if reserves_df is not None else None
    icon, msg = get_alert_level("Bank Reserves", reserves_val)
    summary_cols[1].markdown(f"**Reserves** {icon}<br>{msg}", unsafe_allow_html=True)
    # SOFR
    sofr_val = get_latest_value(sofr_df, sofr_df.columns[0]) if sofr_df is not None else None
    icon, msg = get_alert_level("SOFR", sofr_val)
    summary_cols[2].markdown(f"**SOFR** {icon}<br>{msg}", unsafe_allow_html=True)
    # SRF
    srf_val = get_latest_value(srf_df, srf_df.columns[0]) if srf_df is not None else None
    icon, msg = get_alert_level("SRF", srf_val)
    summary_cols[3].markdown(f"**SRF** {icon}<br>{msg}", unsafe_allow_html=True)
    # Treasury
    treasury_val = get_latest_value(treasury_df, treasury_df.columns[0]) if treasury_df is not None else None
    icon, msg = get_alert_level("Treasury", treasury_val)
    summary_cols[4].markdown(f"**Treasury** {icon}<br>{msg}", unsafe_allow_html=True)
    # Treasury
    treasury_val = get_latest_value(treasury_df, treasury_df.columns[0]) if treasury_df is not None else None
    icon, msg = get_alert_level("Treasury", treasury_val)
    summary_cols[4].markdown(f"**Treasury** {icon}<br>{msg}", unsafe_allow_html=True)
reserves_fetcher = ReservesFetcher()
sofr_fetcher = SOFRFetcher()
srf_fetcher = SRFFetcher()
treasury_fetcher = TreasuryFetcher()


# Load data from CSVs (already generated by dashboard.py)
data_dir = os.path.join(os.path.dirname(__file__), "data")
def load_data(path, fetcher=None):
    # Try API fetcher first if provided
    if fetcher is not None:
        try:
            df = fetcher.fetch_data() if hasattr(fetcher, 'fetch_data') else fetcher()
            if df is not None and not df.empty:
                return df, "API"
        except Exception:
            pass
    # Fallback to file
    try:
        df = pd.read_csv(path)
        if df is not None and not df.empty:
            return df, "File"
    except Exception:
        pass
    return None, None

onrrp_df, onrrp_source = load_data(os.path.join(data_dir, "onrrp_data.csv"), onrrp_fetcher)
reserves_df, reserves_source = load_data(os.path.join(data_dir, "reserves_data.csv"), reserves_fetcher)
sofr_df, sofr_source = load_data(os.path.join(data_dir, "sofr_data.csv"), sofr_fetcher)
srf_df, srf_source = load_data(os.path.join(data_dir, "srf_data.csv"), srf_fetcher)
treasury_df, treasury_source = load_data(os.path.join(data_dir, "treasury_data.csv"), treasury_fetcher)

# --- ALERT LOGIC & SUMMARY PANEL ---
def get_alert_level(indicator, value):
    if indicator == "ON RRP":
        if value is None:
            return "🔴", "No data"
        if value > THRESHOLDS['onrrp_stress'] * 1e9:
            return "⚠️", f"Stress: {value/1e9:.1f}B > {THRESHOLDS['onrrp_stress']}B"
        return "🟢", f"Normal: {value/1e9:.1f}B"
    if indicator == "Bank Reserves":
        if value is None:
            return "🔴", "No data"
        if value < THRESHOLDS['reserves_low'] * 1e9:
            return "⚠️", f"Stress: {value/1e9:.1f}B < {THRESHOLDS['reserves_low']}B"
        return "🟢", f"Normal: {value/1e9:.1f}B"
    if indicator == "SOFR":
        if value is None:
            return "🔴", "No data"
        if value > THRESHOLDS['sofr_spike']:
            return "⚠️", f"Stress: {value:.3f} > {THRESHOLDS['sofr_spike']:.3f}"
        return "🟢", f"Normal: {value:.3f}"
    if indicator == "SRF":
        if value is None:
            return "🔴", "No data"
        if value > THRESHOLDS['srf_usage'] * 1e9:
            return "🚨", f"Emergency: {value/1e9:.1f}B > {THRESHOLDS['srf_usage']}B"
        return "🟢", f"Normal: {value/1e9:.1f}B"
    if indicator == "Treasury":
        if value is None:
            return "🔴", "No data"
        if value > THRESHOLDS['treasury_issuance_high'] * 1e9:
            return "⚠️", f"Stress: {value/1e9:.1f}B > {THRESHOLDS['treasury_issuance_high']}B"
        return "🟢", f"Normal: {value/1e9:.1f}B"
    return "🔴", "No data"

def get_latest_value(df, col):
    if df is None or col not in df.columns:
        return None
    try:
        return float(df[col].dropna().iloc[-1])
    except Exception:
        return None

with st.container():
    st.subheader("System Stress Summary")
    summary_cols = st.columns(5)
    # ON RRP
    onrrp_val = get_latest_value(onrrp_df, onrrp_df.columns[0]) if onrrp_df is not None else None
    icon, msg = get_alert_level("ON RRP", onrrp_val)
    summary_cols[0].markdown(f"**ON RRP** {icon}<br>{msg}", unsafe_allow_html=True)
    # Bank Reserves
    reserves_val = get_latest_value(reserves_df, reserves_df.columns[0]) if reserves_df is not None else None
    icon, msg = get_alert_level("Bank Reserves", reserves_val)
    summary_cols[1].markdown(f"**Reserves** {icon}<br>{msg}", unsafe_allow_html=True)
    # SOFR
    sofr_val = get_latest_value(sofr_df, sofr_df.columns[0]) if sofr_df is not None else None
    icon, msg = get_alert_level("SOFR", sofr_val)
    summary_cols[2].markdown(f"**SOFR** {icon}<br>{msg}", unsafe_allow_html=True)
    # SRF
    srf_val = get_latest_value(srf_df, srf_df.columns[0]) if srf_df is not None else None
    icon, msg = get_alert_level("SRF", srf_val)
    summary_cols[3].markdown(f"**SRF** {icon}<br>{msg}", unsafe_allow_html=True)
    # Treasury
    treasury_val = get_latest_value(treasury_df, treasury_df.columns[0]) if treasury_df is not None else None
    icon, msg = get_alert_level("Treasury", treasury_val)
    summary_cols[4].markdown(f"**Treasury** {icon}<br>{msg}", unsafe_allow_html=True)



col1, col2 = st.columns([2, 3])
with st.container():
    st.header("ON RRP Operations")
    st.markdown("""
        **ON RRP** (Overnight Reverse Repo) operations are conducted by the NY Fed to manage short-term liquidity. Data includes operation date, total accepted amount (billions), and number of counterparties.
    """)

    # User controls for ON RRP data selection
    onrrp_mode = st.radio(
        "Select data mode:",
        ["Latest", "Last N Operations", "Date Range"],
        horizontal=True
    )
    fetcher = ONRRPFetcher()
    onrrp_df = None
    if onrrp_mode == "Latest":
        onrrp_df = fetcher.fetch_data(mode="latest")
    elif onrrp_mode == "Last N Operations":
        last_n = st.number_input("Number of operations:", min_value=1, max_value=60, value=7)
        onrrp_df = fetcher.fetch_data(mode="last_n", last_n=last_n)
    elif onrrp_mode == "Date Range":
        start_date = st.date_input("Start date:")
        end_date = st.date_input("End date:")
        if start_date and end_date:
            onrrp_df = fetcher.fetch_data(
                mode="date_range",
                start_date=pd.to_datetime(start_date),
                end_date=pd.to_datetime(end_date)
            )

    # Data source indicator
    st.write(f"Data Source: :globe_with_meridians: NY Fed API")

    # Display ON RRP data
    if onrrp_df is not None and not onrrp_df.empty:
        st.dataframe(onrrp_df)
        st.line_chart(onrrp_df.set_index("Date")["Accepted_Billions"])
        st.write(f"Latest operation: {onrrp_df['Date'].iloc[-1].date()} | Accepted: ${onrrp_df['Accepted_Billions'].iloc[-1]:.2f}B | Counterparties: {int(onrrp_df['Counterparties'].iloc[-1])}")
        # Export option
        csv = onrrp_df.to_csv(index=False).encode()
        st.download_button("Download CSV", csv, "on_rrp.csv", "text/csv")
    else:
        st.warning("ON RRP data not available or no results for selected parameters.")



col1, col2 = st.columns([2, 3])
with col1:
    indicator = "🟢" if reserves_source == "API" else ("🟡" if reserves_source == "File" else "🔴")
    st.header(f"Bank Reserves Data {indicator}")
    if reserves_df is None:
        st.warning("Bank Reserves data not available from source.")
    else:
        if "date" in reserves_df.columns:
            reserves_df = reserves_df.set_index("date")
        selected_reserves_col = st.selectbox("Select Reserves column to plot", [col for col in reserves_df.columns])
        st.info(get_field_description("Bank Reserves", selected_reserves_col))
with col2:
    if reserves_df is not None:
        st.line_chart(reserves_df[selected_reserves_col])



col1, col2 = st.columns([2, 3])
with col1:
    indicator = "🟢" if sofr_source == "API" else ("🟡" if sofr_source == "File" else "🔴")
    st.header(f"SOFR Data {indicator}")
    if sofr_df is None:
        st.warning("SOFR data not available from source.")
    else:
        if "date" in sofr_df.columns:
            sofr_df = sofr_df.set_index("date")
        selected_sofr_col = st.selectbox("Select SOFR column to plot", [col for col in sofr_df.columns])
        st.info(get_field_description("SOFR", selected_sofr_col))
with col2:
    if sofr_df is not None:
        st.line_chart(sofr_df[selected_sofr_col])



col1, col2 = st.columns([2, 3])
with col1:
    indicator = "🟢" if srf_source == "API" else ("🟡" if srf_source == "File" else "🔴")
    st.header(f"SRF Data {indicator}")
    if srf_df is None:
        st.warning("SRF data not available from source.")
    else:
        if "date" in srf_df.columns:
            srf_df = srf_df.set_index("date")
        selected_srf_col = st.selectbox("Select SRF column to plot", [col for col in srf_df.columns])
        st.info(get_field_description("SRF", selected_srf_col))
with col2:
    if srf_df is not None:
        st.line_chart(srf_df[selected_srf_col])



col1, col2 = st.columns([2, 3])
with col1:
    indicator = "🟢" if treasury_source == "API" else ("🟡" if treasury_source == "File" else "🔴")
    st.header(f"Treasury Issuance Data {indicator}")
    if treasury_df is None:
        st.warning("Treasury data not available from source.")
    else:
        if "date" in treasury_df.columns:
            treasury_df = treasury_df.set_index("date")
        selected_treasury_col = st.selectbox("Select Treasury column to plot", [col for col in treasury_df.columns])
        st.info(get_field_description("Treasury", selected_treasury_col))
with col2:
    if treasury_df is not None:
        st.line_chart(treasury_df[selected_treasury_col])

st.success("Dashboard loaded. Use the sidebar to select data ranges and analysis options (to be added).")
