import streamlit as st
import pandas as pd
import os
from src.fetch_onrrp import ONRRPFetcher
from src.fetch_reserves import ReservesFetcher
from src.fetch_sofr import SOFRFetcher
from src.fetch_srf import SRFFetcher
from src.fetch_treasury import TreasuryFetcher

st.set_page_config(page_title="Liquidity Stress Dashboard", layout="wide")
st.title("Federal Liquidity Stress Dashboard")

# Data fetchers
onrrp_fetcher = ONRRPFetcher()
reserves_fetcher = ReservesFetcher()
sofr_fetcher = SOFRFetcher()
srf_fetcher = SRFFetcher()
treasury_fetcher = TreasuryFetcher()

# Load data from CSVs (already generated by dashboard.py)
data_dir = os.path.join(os.path.dirname(__file__), "data")
onrrp_df = pd.read_csv(os.path.join(data_dir, "onrrp_data.csv"))
reserves_df = pd.read_csv(os.path.join(data_dir, "reserves_data.csv"))
sofr_df = pd.read_csv(os.path.join(data_dir, "sofr_data.csv"))
srf_df = pd.read_csv(os.path.join(data_dir, "srf_data.csv"))
treasury_df = pd.read_csv(os.path.join(data_dir, "treasury_data.csv"))

st.header("ON RRP Data")
if "date" in onrrp_df.columns:
	onrrp_df = onrrp_df.set_index("date")
selected_onrrp_col = st.selectbox("Select ON RRP column to plot", [col for col in onrrp_df.columns])
st.line_chart(onrrp_df[selected_onrrp_col])

st.header("Bank Reserves Data")
if "date" in reserves_df.columns:
	reserves_df = reserves_df.set_index("date")
selected_reserves_col = st.selectbox("Select Reserves column to plot", [col for col in reserves_df.columns])
st.line_chart(reserves_df[selected_reserves_col])

st.header("SOFR Data")
if "date" in sofr_df.columns:
	sofr_df = sofr_df.set_index("date")
selected_sofr_col = st.selectbox("Select SOFR column to plot", [col for col in sofr_df.columns])
st.line_chart(sofr_df[selected_sofr_col])

st.header("SRF Data")
if "date" in srf_df.columns:
	srf_df = srf_df.set_index("date")
selected_srf_col = st.selectbox("Select SRF column to plot", [col for col in srf_df.columns])
st.line_chart(srf_df[selected_srf_col])

st.header("Treasury Issuance Data")
if "date" in treasury_df.columns:
	treasury_df = treasury_df.set_index("date")
selected_treasury_col = st.selectbox("Select Treasury column to plot", [col for col in treasury_df.columns])
st.line_chart(treasury_df[selected_treasury_col])

st.success("Dashboard loaded. Use the sidebar to select data ranges and analysis options (to be added).")
